name: ecc24_env
channels:
  - pytorch
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - anyio=4.0.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.13.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=6.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.7.22
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.0.5
  - cycler=0.11.0
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=2.0.1
  - filelock=3.9.0
  - fonttools=4.25.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - giflib=5.2.1
  - icu=73.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.26.0
  - ipython=8.17.2
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.2
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.9.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.8
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.9
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lerc=3.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libuv=1.44.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpmath=1.3.0
  - munkres=1.1.4
  - nb_conda_kernels=2.3.1
  - nbclient=0.8.0
  - nbconvert-core=7.11.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.8
  - networkx=3.1
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openjpeg=2.4.0
  - openssl=3.1.4
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.0.0
  - ply=3.11
  - prometheus_client=0.18.0
  - prompt-toolkit=3.0.41
  - prompt_toolkit=3.0.41
  - psutil=5.9.5
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.1.1
  - pytorch-mutex=1.0
  - pytz=2023.3.post1
  - pywin32=306
  - pywinpty=2.0.12
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qt-main=5.15.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.12.0
  - send2trash=1.8.2
  - setuptools=68.0.0
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.6.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - terminado=0.18.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.13.0
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.1.0
  - vc=14.2
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - wcwidth=0.2.10
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.4
  - wheel=0.41.2
  - widgetsnbextension=4.0.9
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - casadi==3.6.4
      - do-mpc==4.6.2
      - scipy==1.11.3
